### ISSUE TITLE
[Bug] New Search Engine on EXH

### ISSUE THREAD

**Issue by Lenoyr** [az4521/TachiyomiAZ#55] opened 2022-11-04 04:37 UTC
---

### Device information
* Tachiyomi version: V8.7.2-AZ
* Android version: Android 10 QKQ1 .20114.002
* Device: Redmi Note 8

## Steps to reproduce
1.  Go to Browse for extension
2. Click in extension
3. Go to page 2 

### Expected behavior
go to page 2

### Actual behavior
Doesn’t advance the page 

### Other details
The search results is now done by gallery ID (GID) ranges rather than "pages"
More info: https://forums.e-hentai.org/index.php?showtopic=261743

**Comment by az4521** [comment] 2022-11-05 17:45
fixed in the dev build, https://crafty.moe/tachiyomiAZ.apk

let me know if there are still any issues with it

**Closed by az4521** 2022-11-05 17:45 UTC
Labels: bug

**Comment by synthicyde** [comment] 2022-12-26 08:37
> fixed in the dev build, https://crafty.moe/tachiyomiAZ.apk
> 
> let me know if there are still any issues with it

Just installed and it seems to be working as intended. I'm getting the pages to load as normal. I'll scroll around and see if I run into any issues but this fix seemed to work.
