### ISSUE TITLE
[Bug] spyfakku extension does not load the series

### ISSUE THREAD

**Issue by sillysack69** [az4521/TachiyomiAZ#101] opened 2024-08-08 10:50 UTC
### Device information
* Tachiyomi version: 8.8.1-AZ
* Android version: 13
* Device: Xiaomi Redmi note 12 4g

## Steps to reproduce
1. Open the sources from side panel
2. Open spyfakku from the list
3. Each series loads fine
4. Select any series from the list
5. Series does not load

### Expected behavior
Should load thumbnail and series information with chapters as expected.

### Actual behavior
It throws the following error:
![Screenshot_2024-08-08-15-45-32-092_eu kanade tachiyomi az](https://github.com/user-attachments/assets/6acfe1b3-a58b-48f7-a1e7-71462de8af8b)

### Additional information
The extension works as expected on Mihon 0.16.5

**Comment by chs-rsargees** [comment] 2024-08-08 17:42
try the dev build, this issue is fixed there

 https://crafty.moe/tachiyomiAZ.apk

**Comment by az4521** [comment] 2024-08-08 17:43
this should be fixed in the dev build, get it here

https://crafty.moe/tachiyomiAZ.apk

**Comment by sillysack69** [comment] 2024-08-09 08:51
After installing the dev build from above, I get the following error
![Screenshot_2024-08-09-13-47-54-420_eu kanade tachiyomi az](https://github.com/user-attachments/assets/881ceb9d-7e35-48a4-878b-ac5f56cb18fe)
Now I can't even get the option to select a series. Now it has it gotten worse?

**Comment by az4521** [comment] 2024-08-09 15:35
I just tested the extension in mihon, and it has the same error there, so the problem is with the extension, not tachiyomiaz. I guess the site changed and the extension broke at the same time you updated to the dev build.

**Closed by az4521** 2024-08-09 15:35 UTC
Labels: bug

**Comment by sillysack69** [comment] 2024-08-09 16:46
Can't test this right now then but the build probably works now. Thanks 👍
