### ISSUE TITLE
[Bug] Gifs not working

### ISSUE THREAD

**Issue by random-existence** [az4521/TachiyomiAZ#95] opened 2024-05-16 10:01 UTC
### Device information
* Tachiyomi version: v8.8.1-AZ
* Android version: 9
* Device: Samsung Galaxy S8+

## Steps to reproduce
Opening any animated gif

### Expected behavior
All gifs load normally

### Actual behavior
All gifs show as static pictures

### Other details
Even downloaded gifs don't work, but the prior version [v8.8.0-AZ] works perfectly

**Comment by az4521** [comment] 2024-05-17 00:47
duplicate of #93 

fixed in https://github.com/az4521/TachiyomiAZ/commit/893415ff53fcffafca554af30f0522df92048b25

**Closed by az4521** 2024-05-17 00:47 UTC
Labels: bug
